export const premierLeagueTeams = {
    Arsenal: require('../img/uk/arsenal.png'),
    AstonVilla: require('../img/uk/astonvilla.png'),
    Bournemouth: require('../img/uk/bournemouth.png'),
    Brentford: require('../img/uk/brentford.png'),
    BrightonandHoveAlbion: require('../img/uk/brighton.png'),
    Burnley: require('../img/uk/burnley.png'),
    Chelsea: require('../img/uk/chelsea.png'),
    CrystalPalace: require('../img/uk/crystalpalace.png'),
    Everton: require('../img/uk/everton.png'),
    Fulham: require('../img/uk/fulham.png'),
    Liverpool: require('../img/uk/liverpool.png'),
    LutonTown: require('../img/uk/luton_town.png'),
    ManchesterCity: require('../img/uk/manchestercity.png'),
    ManchesterUnited: require('../img/uk/manchesterunited.png'),
    NewcastleUnited: require('../img/uk/newcastle.png'),
    NottinghamForest: require('../img/uk/nottingham_forest.png'),
    SheffieldUnited: require('../img/uk/sheffield.png'),
    TottenhamHotspur: require('../img/uk/tottenham.png'),
    WestHamUnited: require('../img/uk/westham.png'),
    Wolves: require('../img/uk/wolves.png'),
  };
  
  export const serieATeams = {
    AtalantaBC: require('../img/it/atalanta.png'),
    Bologna: require('../img/it/bologna.png'),
    Cagliari: require('../img/it/cagliari.png'),
    Empoli: require('../img/it/empoli.png'),
    Fiorentina: require('../img/it/fiorentina.png'),
    Frosinone: require('../img/it/frosinone.png'),
    Genoa: require('../img/it/genoa.png'),
    HellasVeronaFC: require('../img/it/hellasverona.png'),
    FCInternazionale: require('../img/it/inter.png'),
    Juventus: require('../img/it/juventus.png'),
    Lazio: require('../img/it/lazio.png'),
    Lecce: require('../img/it/lecce.png'),
    ACMilan: require('../img/it/milan.png'),
    ACMonza: require('../img/it/monza.png'),
    Napoli: require('../img/it/napoli.png'),
    ASRoma: require('../img/it/roma.png'),
    Salernitana: require('../img/it/salernitana.png'), 
    Sassuolo: require('../img/it/sassuolo.png'), 
    Torino: require('../img/it/torino.png'),
    Udinese: require('../img/it/udinese.png'), 
  };
  
  export const bundesligaTeams = {
    Augsburg: require('../img/de/augsburgo.png'),
    BayerLeverkusen: require('../img/de/bayerleverkusen.png'),
    BayernMunich: require('../img/de/bayernmunchen.png'),
    BorussiaMonchengladbach: require('../img/de/bmonchengladbach.png'),
    Bochum: require('../img/de/bochum.png'),
    BorussiaDortmund: require('../img/de/borussiadortmund.png'),
    Darmstadt: require('../img/de/darmstadt98​.png'),
    EintrachtFrankfurt: require('../img/de/eintrachtfrankfurt.png'),
    Freiburg: require('../img/de/freiburg.png'),
    FCHeidenheim: require('../img/de/heidenheim.png'),
    Hoffenheim: require('../img/de/hoffenheim.png'),
    FCKoln: require('../img/de/koln.png'),
    Mainz05: require('../img/de/mainz05.png'),
    RBLeipzig: require('../img/de/rbleipzig.png'),
    VfBStuttgart: require('../img/de/stuttgart.png'),
    UnionBerlin: require('../img/de/unionberlin.png'),
    WerderBremen: require('../img/de/werderbremen.png'),
    Wolfsburg: require('../img/de/wolfsburg.png'),
  };
  
  export const ligaArgentinaTeams = {
    ArgentinosJuniors: require('../img/ar/argentinos.png'),
    AtleticoTucuman: require('../img/ar/atleticotucuman.png'),
    Banfield: require('../img/ar/banfield.png'),
    BarracasCentral: require('../img/ar/barracas.png'),
    Belgrano: require('../img/ar/belgrano.png'),
    BocaJuniors: require('../img/ar/boca.png'),
    CentralCordoba: require('../img/ar/centralcordoba.png'),
    DefensayJusticia: require('../img/ar/defensa.png'),
    EstudiantesdeLaPlata: require('../img/ar/estudiantes.png'),
    GimnasiaLaPlata: require('../img/ar/gimnasia.png'),
    GodoyCruz: require('../img/ar/godoycruz.png'),
    Huracan: require('../img/ar/huracan.png'),
    Independiente: require('../img/ar/independiente.png'),
    IndependienteRivadavia: require('../img/ar/independienteriv.png'),
    Instituo: require('../img/ar/instituto.png'),
    Lanus: require('../img/ar/lanus.png'),
    NewellsOldBoys: require('../img/ar/newells.png'),
    Platense: require('../img/ar/platense.png'),
    RacingClub: require('../img/ar/racing.png'),
    DeportivoRiestra: require('../img/ar/riestra.png'),
    RiverPlate: require('../img/ar/river.png'),
    RosarioCentral: require('../img/ar/rosariocentral.png'),
    SanLorenzo: require('../img/ar/sanlorenzo.png'),
    Sarmiento: require('../img/ar/sarmiento.png'),
    CATalleresdeCordoba: require('../img/ar/talleres.png'),
    CATigre: require('../img/ar/tigre.png'),
    UnionSantaFe: require('../img/ar/union.png'),
    VelezSarsfield: require('../img/ar/velez.png'),
  };
  
  export const laLigaTeams = {
    Alaves: require('../img/es/alaves.png'),
    Almeria: require('../img/es/almeria.png'),
    AthleticClubBilbao: require('../img/es/athletic.png'),
    AtleticoMadrid: require('../img/es/atlmadrid.png'),
    Barcelona: require('../img/es/barcelona.png'),
    RealBetis: require('../img/es/betis.png'),
    Cadiz: require('../img/es/cadiz.png'),
    CeltaVigo: require('../img/es/celta.png'),
    Getafe: require('../img/es/getafe.png'),
    Girona: require('../img/es/girona.png'),
    GranadaCF: require('../img/es/granada.png'),
    Mallorca: require('../img/es/mallorca.png'),
    Osasuna: require('../img/es/osasuna.png'),
    RayoVallecano: require('../img/es/rayovallecano.png'),
    RealMadrid: require('../img/es/realmadrid.png'),
    RealSociedad: require('../img/es/realsociedad.png'),
    Sevilla: require('../img/es/sevilla.png'),
    LasPalmas: require('../img/es/udlaspalmas.png'),
    Valencia: require('../img/es/valencia.png'),
    VillarrealCF: require('../img/es/villarreal.png'),
  };
  
  export const ligue1Teams = {
    Amiens: require('../img/fr/amiens.png'),
    Clermont: require('../img/fr/clermont.png'),
    LeHavre: require('../img/fr/havre.png'),
    Lille: require('../img/fr/lille.png'),
    Lorient: require('../img/fr/lorient.png'),
    Metz: require('../img/fr/metz.png'),
    ASMonaco: require('../img/fr/monaco.png'),
    MontpellierHSC: require('../img/fr/montpellier.png'),
    Nantes: require('../img/fr/nantes.png'),
    Nice: require('../img/fr/niza.png'),
    Marseille: require('../img/fr/olimpiquemarsella.png'),
    Lyon: require('../img/fr/olympiquelyon.png'),
    ParisSaintGermain: require('../img/fr/psg.png'),
    Strasbourg: require('../img/fr/racingetrasburgo.png'),
    Lens: require('../img/fr/racinglens.png'),
    Rennes: require('../img/fr/rennais.png'),
    Brest: require('../img/fr/stadebretois.png'),
    Reims: require('../img/fr/stadereims.png'),
    ToulouseFC: require('../img/fr/toulouse.png'),
  };